import Head from "next/head";
import ChannelsList from "../components/ChannelsList";
import Subtitles from "../components/Subtitles";

export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Tv Argentina</title>
      </Head>
      <Subtitles label="Lista de canales" />
      <ChannelsList />
    </div>
  );
}
